server:
  port: 8100
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka/ # http://112.124.59.38:8761/eureka/ # http://121.40.223.116:8761/eureka/ #
spring:
  application:
    name: emt-bpay-feign
multipart:
  enabled: true
  max-file-size: 50mb
  max-request-size: 50mb
feign:
  hystrix:
    enabled: false