spring:
  application:
    name: emt-gateway
server:
  port: 9900
zuul:
  routes:
    bpay:
      path: /bpay/**
      serviceId: emt-bpay-feign
  ignored-services: '*'
  host:
    max-total-connections: 500
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka/ # http://121.40.223.116:8761/eureka/ #  http://112.124.59.38:8761/eureka/ #
  instance:
    preferIpAddress: true
    metadata-map:
      cluster: EMT-BPAY-SERVICE
