spring:
  application:
    name: emt-bpay-service
server:
  port: 8091
eureka:
  client:
      service-url:
        defaultZone: http://127.0.0.1:8761/eureka/ # http://112.124.59.38:8761/eureka/ # http://121.40.223.116:8761/eureka/ #
multipart:
  enabled: true
  max-file-size: 50mb
  max-request-size: 50mb