spring:
  application:
    name: emt-epay-server
  datasource:
    name: emt_epay
    url:  jdbc:sqlserver://112.124.59.38:1433;DatabaseName=emt_epay
    username: sa
    password: opqhjb-*#06#
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    max-active: 20
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
multipart:
  enabled: true
  max-file-size: 50mb
  max-request-size: 50mb
server:
  port: 8899
eureka:
    client:
      service-url:
        defaultZone: http://127.0.0.1:8761/eureka/
mybatis:
  type-aliases-package: com.emt.epay.dao.entity
  mapper-locations: classpath*:mapping/*.xml